---
title: "Cricket Analysis"
author: "Kathirmani Sukumar"
date: "August 21, 2017"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read data 

```{r, message=FALSE, warning=FALSE}
odi = read.csv("D://datasets//odi-batting.csv")
library(knitr)
library(dplyr)
kable(odi[1:5, ])
```

## Top ten players by total runs
```{r, message=FALSE, warning=FALSE}
top_players = odi %>% group_by(Player) %>% summarise(Total_Runs = sum(Runs, na.rm=TRUE), Country=first(Country)) %>% arrange(-Total_Runs)
kable(top_players[1:5, ])
```


```{r, message=FALSE, warning=FALSE}
odi_centuries = filter(odi, Runs>99)
players_centuries = odi_centuries %>% group_by(Player) %>% summarise(Centuries = n())
players_centuries = players_centuries %>% arrange(-Centuries)
head(players_centuries)
```
## Countrywise total number of players
```{r, message=FALSE, warning=FALSE}
country_players = odi %>% group_by(Country) %>% summarise(Count_Players=n_distinct(Player)) %>% arrange(-Count_Players)
head(country_players)
```
## Groundwise centuries
```{r, message=FALSE, warning=FALSE}
rows_centuries = filter(odi, Runs>99)
grounds_centuries = rows_centuries %>% group_by(Ground) %>% summarise(count_centuries=n()) %>% arrange(-count_centuries)
kable(head(grounds_centuries))
```

## Analyse Sachin's Performance
```{r, message=FALSE, warning=FALSE}
# Number of ducks agains each country
rows_sachin = filter(odi, Player=='Sachin R Tendulkar')
rows_sachin_ducks = filter(rows_sachin, Runs==0)
versus_ducks = rows_sachin_ducks %>% group_by(Versus) %>% summarise(ducks=n()) %>% arrange(-ducks)
kable(versus_ducks)
```


### Number of centuries against each country
```{r, message=FALSE, warning=FALSE}
rows_sachin_centuries = filter(rows_sachin, Runs>99)
versus_centuries = rows_sachin_centuries %>% group_by(Versus) %>% summarise(centuries=n()) %>% arrange(-centuries)
kable(versus_centuries)
```

### Number of times missed century
```{r, message=FALSE, warning=FALSE}
rows_sachin_missed = filter(rows_sachin, Runs>90, Runs<100)
dim(rows_sachin_missed)
```

### Number of fifties
```{r, message=FALSE, warning=FALSE}
rows_sachin_fifties = filter(rows_sachin, Runs>49, Runs<100)
dim(rows_sachin_fifties)
```

```{r, message=FALSE, warning=FALSE}
odi = odi %>% mutate(ducks=if_else(Runs==0, 1, 0))
odi = odi %>% mutate(centuries=if_else(Runs>99, 1, 0))
odi = odi %>% mutate(missed=if_else(Runs>90 & Runs<100, 1, 0))
odi = odi %>% mutate(fifties=if_else(Runs>50 & Runs<100, 1, 0))


players_summary = odi %>% group_by(Player) %>% summarise(Total_Runs=sum(Runs, na.rm=TRUE), Centuries=sum(centuries, na.rm=TRUE ), ducks=sum(ducks, na.rm=TRUE), fifties=sum(fifties, na.rm=TRUE), Missed_Centuries=sum(missed, na.rm=TRUE)) %>% arrange(-Total_Runs)
kable(head(players_summary))
```

### Sachin's Performance
```{r, message=FALSE, warning=FALSE}
library(ggplot2)
sachin_rows = filter(odi, Player=='Sachin R Tendulkar')
ggplot(sachin_rows, aes(x=Runs, y=ScoreRate))  + geom_point() + geom_smooth()
```

### Sehwag's Performance
```{r, message=FALSE, warning=FALSE}
sehwag_rows = filter(odi, Player=='Virender Sehwag')
ggplot(sehwag_rows, aes(x=Runs, y=ScoreRate))  + geom_point() + geom_smooth()
```

### Indian Team Performance
```{r, message=FALSE, warning=FALSE}
india_rows = filter(odi, Country=='India')
dim(india_rows)
players_runs = india_rows %>% group_by(Player) %>% summarise(total_runs=sum(Runs, na.rm=TRUE)) %>% arrange(-total_runs)
top_players_names = head(players_runs$Player, 10)
top_players_names

top_players_rows = odi[odi$Player %in% top_players_names, ]
ggplot(top_players_rows, aes(x=Runs, y=ScoreRate)) + geom_point() + geom_smooth() + facet_wrap(~Player) 
```

### Indian Team Performance
```{r, message=FALSE, warning=FALSE}
players_runs = odi %>% group_by(Player) %>% summarise(total_runs=sum(Runs, na.rm=TRUE)) %>% arrange(-total_runs)
top_players_names = head(players_runs$Player, 10)
top_players_names

top_players_rows = odi[odi$Player %in% top_players_names, ]
ggplot(top_players_rows, aes(x=Runs, y=ScoreRate)) + geom_point() + geom_smooth() + facet_wrap(~Player) 
```



### Indian Players Performance
```{r, message=FALSE, warning=FALSE}
odi$Date = as.Date(odi$MatchDate, format="%m-%d-%Y")
odi$year = format(odi$Date, '%Y')
odi$weekday = format(odi$Date, '%A')

# Extract data for India
india_rows = filter(odi, Country=='India')
dim(india_rows)
# Identify top 10 players by total matches
matches_players = india_rows %>% group_by(Player) %>% summarise(total_matches=n()) %>% arrange(-total_matches)
matches_players
top10_players_names = head(matches_players$Player, 10)

# Filter data again for these ten players
top10_players_rows = india_rows[india_rows$Player %in% top10_players_names, ]

# For each player calculate total runs across year
summary = top10_players_rows %>% group_by(Player, year) %>% summarise(total_runs=sum(Runs, na.rm=TRUE))

ggplot(summary, aes(x=year, y=total_runs)) + geom_bar(stat='identity') + facet_wrap(~Player)
```