---
title: "Modi Twitter Analysis"
author: "Kathirmani Sukumar"
date: "August 28, 2017"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Preview Data
```{r, message=FALSE, warning=FALSE}
setwd('C://Users//Kathirmani//Desktop//manipal_eda')
modi = read.csv('narendramodi_tweets.csv')
library(dplyr)
library(ggplot2)
dim(modi)
```

```{r, message=FALSE, warning=FALSE}
source_summary = modi %>% group_by(source) %>% summarise(count=n(), avg_retweets = mean(retweets_count, na.rm=TRUE), avg_likes=mean(favorite_count, na.rm=TRUE))
source_summary

ggplot(source_summary, aes(x=source, y=count, fill=-avg_retweets)) + geom_bar(stat='identity') + coord_flip()
```

```{r, message=FALSE, warning=FALSE}
ggplot(source_summary, aes(x=source, y=count, fill=-avg_likes)) + geom_bar(stat='identity') + coord_flip()

```

```{r, message=FALSE, warning=FALSE}
modi$date = as.Date(modi$created_at, format='%Y-%m-%d %H:%M:%S') 
modi$year = format(modi$date, '%Y')
modi$month = format(modi$date, '%m')
modi$day = format(modi$date, '%d')
modi$weekday = format(modi$date, '%A')
modi$year_month = format(modi$date, '%Y-%m')
modi$day_month_year = format(modi$date, '%Y-%m-%d')
head(select(modi, date, year, month, day, weekday))

tweets_months = modi %>% group_by(year_month) %>% summarise(tweets_count=n())
ggplot(tweets_months, aes(x=year_month,y=tweets_count, group=1))+ geom_bar(stat='identity') + geom_line()
```

```{r, message=FALSE, warning=FALSE}
hashtags_daywise = modi %>% group_by(day_month_year) %>% summarise(hashtags_count=sum(hashtags_count))
ggplot(hashtags_daywise, aes(x=day_month_year,y=hashtags_count, group=1)) + geom_line()
```

```{r, message=FALSE, warning=FALSE}
ggplot(modi, aes(x=favorite_count, y=retweets_count, color=source)) + geom_point() + geom_smooth()
```

```{r}
text = tolower(modi$text)
text_clean = gsub(x=text, pattern = '[^[:alpha:]] ', replacement = '')

words_list = strsplit(text_clean, ' ')
words = unlist(words_list)
words_freq = table(words)
df_words_freq = as.data.frame(words_freq)
df_words_freq = df_words_freq %>% arrange(-Freq)
View(df_words_freq)
library(wordcloud)
```

